//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatFactura
    {
        public int IdFactura { get; set; }
        public int IdProducto { get; set; }
        public int IdCliente { get; set; }
        public int Cantidad { get; set; }
        public Nullable<double> TotalCompra { get; set; }
        public System.DateTime FechaCompra { get; set; }
    
        public virtual CatCliente CatCliente { get; set; }
        public virtual CatProducto CatProducto { get; set; }
    }
}
