//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatInventarioP
    {
        public int IdInventario { get; set; }
        public int IdProducto { get; set; }
        public int PInventario { get; set; }
    
        public virtual CatProducto CatProducto { get; set; }
    }
}
